name: Caller Workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - test-PR-branch
    paths: .github/workflows/caller.yaml
jobs:
  call-child-workflow:
    uses: ./.github/workflows/child.yaml
    with:
      caller: 'Rudrabrata'
