name: Child Workflow
on: 
  workflow_call:
    inputs:
      caller_name:
        type: string
        required: true
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
    - name: Print Message
      run: echo "Hello ${{inputs.caller_name}}"
