name: Dynamic Input 
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select the version'
        required: true
        default: "v2"
        type: choice
        options:
          - 'v1'
          - 'v2'


jobs:
  generate-options:
    runs-on: ubuntu-latest
    steps:
    - name: Get Input
      run: echo "Selected Input= ${{ github.event.inputs.version }}"
  
